openapi: 3.0.1
info:
  description: "Please have a look at the interfaces of comdirect REST API below.\
    \ Note: Currently it is not possible to request an access token via swagger UI\
    \ tools because of comdirect's proprietary authorization flow. The shown error\
    \ message is due to that circumstance."
  title: comdirect REST API
  version: "20.04"
servers:
- url: https://api.comdirect.de/api
tags:
- name: Banking
- name: Brokerage
- name: Messages
- name: Reports
- name: Session
paths:
  /banking/clients/{user}/v2/accounts/balances:
    get:
      operationId: bankingV2GetAccountBalances
      security:
      - CdSecondary:
        - BANKING_RO
      summary: "Request for account information, including cash balance and buying\
        \ power, for all accounts"
      tags:
      - Banking
  /banking/v1/accounts/{accountId}/transactions:
    get:
      operationId: bankingV1GetAccountTransactions
      security:
      - CdSecondary:
        - BANKING_RO
      summary: Requests and returns a list of transactions for the given account
      tags:
      - Banking
  /banking/v2/accounts/{accountId}/balances:
    get:
      operationId: bankingV2GetAccountBalance
      security:
      - CdSecondary:
        - BANKING_RO
      summary: "Request for account information, including cash balance and buying\
        \ power"
      tags:
      - Banking
  /brokerage/clients/{userId}/v3/depots:
    get:
      operationId: brokerageV3GetDepots
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Request for a list of the master data for the securities accounts of
        the registered user
      tags:
      - Brokerage
  /brokerage/depots/{depotId}/v3/orders:
    get:
      operationId: brokerageV3GetOrders
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Delivers a list of all orders for the given depotId.
      tags:
      - Brokerage
  /brokerage/v1/instruments/{instrumentId}:
    get:
      operationId: brokerageV1GetInstrument
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Request for an instrument's information
      tags:
      - Brokerage
  /brokerage/v3/depots/{depotId}/positions:
    get:
      operationId: brokerageV3GetDepotPositions
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: "Request for securities positions, optionally including only the total\
        \ balance with securities account information"
      tags:
      - Brokerage
  /brokerage/v3/depots/{depotId}/positions/{positionId}:
    get:
      operationId: brokerageV3GetDepotPosition
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Request for retrieving a single position of specific depot.
      tags:
      - Brokerage
  /brokerage/v3/depots/{depotId}/transactions:
    get:
      operationId: brokerageV3GetDepotTransactions
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Depot transactions.
      tags:
      - Brokerage
  /brokerage/v3/orders:
    post:
      operationId: brokerageV3PostOrder
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Order entry.
      tags:
      - Brokerage
  /brokerage/v3/orders/costindicationexante:
    post:
      operationId: brokerageV3GetOrdersCostIndicationExAnte
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Generation of the ex-ante cost indication on the basis of the order
        data.
      tags:
      - Brokerage
  /brokerage/v3/orders/dimensions:
    get:
      operationId: brokerageV3GetOrderDimensions
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Request for the trading venue and order options for a particular instrument
      tags:
      - Brokerage
  /brokerage/v3/orders/prevalidation:
    post:
      operationId: brokerageV3PostOrdersPrevalidation
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Prevalidation of the order
      tags:
      - Brokerage
  /brokerage/v3/orders/validation:
    post:
      operationId: brokerageV3PostOrdersValidation
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Validation of an order entry and triggering of a TAN-Challenge in a
        non-usage case of a Session-TAN.
      tags:
      - Brokerage
  /brokerage/v3/orders/{orderId}:
    delete:
      operationId: brokerageV3DeleteOrder
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Order cancellation.
      tags:
      - Brokerage
    get:
      operationId: brokerageV3GetOrder
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Delivers an order for the given orderId.
      tags:
      - Brokerage
    patch:
      operationId: brokerageV3PatchOrder
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Order modification.
      tags:
      - Brokerage
  /brokerage/v3/orders/{orderId}/costindicationexante:
    post:
      operationId: brokerageV3GetOrderCostIndicationExAnte
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Generation of the ex-ante cost indication on the basis of the order
        data.
      tags:
      - Brokerage
  /brokerage/v3/orders/{orderId}/prevalidation:
    post:
      operationId: brokerageV3PostOrderPrevalidation
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Prevalidation of an order modfication
      tags:
      - Brokerage
  /brokerage/v3/orders/{orderId}/validation:
    post:
      operationId: brokerageV3PostOrderValidation
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Validation of an order modification or order cancellation and triggering
        of a TAN Challenge in a non-usage case of a Session-TAN.
      tags:
      - Brokerage
  /brokerage/v3/quotes:
    post:
      operationId: brokerageV3PostQuoteRequest
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Sends a quote request to a venue
      tags:
      - Brokerage
  /brokerage/v3/quoteticket:
    post:
      operationId: brokerageV3PostQuoteTicket
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Initiates a TAN-Challenge
      tags:
      - Brokerage
  /brokerage/v3/quoteticket/{ticketId}:
    patch:
      operationId: brokerageV3PatchQuoteTicket
      security:
      - CdSecondary:
        - BROKERAGE_RW
      summary: Initiate a TAN-Challange
      tags:
      - Brokerage
  /messages/clients/{user}/v2/documents:
    get:
      operationId: messagesV2GetDocuments
      security:
      - CdSecondary:
        - MESSAGES_RO
      summary: Delivers a list of documents for the customer.
      tags:
      - Messages
  /messages/v2/documents/{documentId}:
    get:
      operationId: messagesV2GetDocument
      security:
      - CdSecondary:
        - MESSAGES_RO
      summary: Delivers a document for the given UUID.
      tags:
      - Messages
  /messages/v2/documents/{documentId}/predocument:
    get:
      operationId: messagesV2GetPredocument
      security:
      - CdSecondary:
        - MESSAGES_RO
      summary: Delivers a predocument for the given UUID.
      tags:
      - Messages
  /reports/participants/{user}/v1/allbalances:
    get:
      operationId: reportsV1GetParticipantBalances
      security:
      - CdSecondary:
        - REPORTS_RO
      summary: List of all balances for a client's own and connected products.
      tags:
      - Reports
  /session/clients/{user}/v1/sessions:
    get:
      operationId: sessionV1GetSession
      security:
      - ResourceOwnerPasswordCredentials:
        - TWO_FACTOR
      - CdSecondary:
        - SESSION_RW
      summary: "Returns the current Session-Objects for the specified client, can\
        \ handle the literal \"user\" for the currently logged in client."
      tags:
      - Session
  /session/clients/{user}/v1/sessions/{session}:
    patch:
      operationId: sessionV1PatchSession
      security:
      - ResourceOwnerPasswordCredentials:
        - TWO_FACTOR
      - CdSecondary:
        - SESSION_RW
      summary: Writes updates to a session
      tags:
      - Session
  /session/clients/{user}/v1/sessions/{session}/validate:
    post:
      operationId: sessionV1PostSessionValidation
      security:
      - ResourceOwnerPasswordCredentials:
        - TWO_FACTOR
      - CdSecondary:
        - SESSION_RW
      summary: Validates the input and checks if the client is able to update the
        current session. An activated session TAN cannot be deactivated in the current
        session. It is necessary to provide a TAN when patching the activation of
        the session TAN.
      tags:
      - Session
components:
  securitySchemes:
    ResourceOwnerPasswordCredentials:
      flows:
        password:
          scopes:
            TWO_FACTOR: Read and write permission for SESSION interfaces
          tokenUrl: https://api.comdirect.de/oauth/token
      type: oauth2
    CdSecondary:
      flows: {}
      type: oauth2
x-original-swagger-version: "2.0"
