/*
comdirect REST API

Please have a look at the interfaces of comdirect REST API below. Note: Currently it is not possible to request an access token via swagger UI tools because of comdirect's proprietary authorization flow. The shown error message is due to that circumstance.

API version: 20.04
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package comdirect

import (
	"encoding/json"
)

// checks if the ListResourceDepot type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListResourceDepot{}

// ListResourceDepot struct for ListResourceDepot
type ListResourceDepot struct {
	Paging *PagingInfo `json:"paging,omitempty"`
	Aggregated map[string]interface{} `json:"aggregated,omitempty"`
	Values []Depot `json:"values,omitempty"`
}

// NewListResourceDepot instantiates a new ListResourceDepot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListResourceDepot() *ListResourceDepot {
	this := ListResourceDepot{}
	return &this
}

// NewListResourceDepotWithDefaults instantiates a new ListResourceDepot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListResourceDepotWithDefaults() *ListResourceDepot {
	this := ListResourceDepot{}
	return &this
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *ListResourceDepot) GetPaging() PagingInfo {
	if o == nil || IsNil(o.Paging) {
		var ret PagingInfo
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourceDepot) GetPagingOk() (*PagingInfo, bool) {
	if o == nil || IsNil(o.Paging) {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *ListResourceDepot) HasPaging() bool {
	if o != nil && !IsNil(o.Paging) {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PagingInfo and assigns it to the Paging field.
func (o *ListResourceDepot) SetPaging(v PagingInfo) {
	o.Paging = &v
}

// GetAggregated returns the Aggregated field value if set, zero value otherwise.
func (o *ListResourceDepot) GetAggregated() map[string]interface{} {
	if o == nil || IsNil(o.Aggregated) {
		var ret map[string]interface{}
		return ret
	}
	return o.Aggregated
}

// GetAggregatedOk returns a tuple with the Aggregated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourceDepot) GetAggregatedOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Aggregated) {
		return map[string]interface{}{}, false
	}
	return o.Aggregated, true
}

// HasAggregated returns a boolean if a field has been set.
func (o *ListResourceDepot) HasAggregated() bool {
	if o != nil && !IsNil(o.Aggregated) {
		return true
	}

	return false
}

// SetAggregated gets a reference to the given map[string]interface{} and assigns it to the Aggregated field.
func (o *ListResourceDepot) SetAggregated(v map[string]interface{}) {
	o.Aggregated = v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *ListResourceDepot) GetValues() []Depot {
	if o == nil || IsNil(o.Values) {
		var ret []Depot
		return ret
	}
	return o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListResourceDepot) GetValuesOk() ([]Depot, bool) {
	if o == nil || IsNil(o.Values) {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *ListResourceDepot) HasValues() bool {
	if o != nil && !IsNil(o.Values) {
		return true
	}

	return false
}

// SetValues gets a reference to the given []Depot and assigns it to the Values field.
func (o *ListResourceDepot) SetValues(v []Depot) {
	o.Values = v
}

func (o ListResourceDepot) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListResourceDepot) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Paging) {
		toSerialize["paging"] = o.Paging
	}
	if !IsNil(o.Aggregated) {
		toSerialize["aggregated"] = o.Aggregated
	}
	if !IsNil(o.Values) {
		toSerialize["values"] = o.Values
	}
	return toSerialize, nil
}

type NullableListResourceDepot struct {
	value *ListResourceDepot
	isSet bool
}

func (v NullableListResourceDepot) Get() *ListResourceDepot {
	return v.value
}

func (v *NullableListResourceDepot) Set(val *ListResourceDepot) {
	v.value = val
	v.isSet = true
}

func (v NullableListResourceDepot) IsSet() bool {
	return v.isSet
}

func (v *NullableListResourceDepot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListResourceDepot(val *ListResourceDepot) *NullableListResourceDepot {
	return &NullableListResourceDepot{value: val, isSet: true}
}

func (v NullableListResourceDepot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListResourceDepot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


